version: '3'

services:

  redis:
      image: "redis:alpine"

      command: redis-server #--requirepass password

      ports:
        - "6379:6379"

      volumes:
        - ./redis/redis-data:/var/lib/redis
        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

      environment:
        - REDIS_REPLICATION_MODE=master

      #networks:
      #  node_net:
      #    ipv4_address: 172.28.1.4

networks:
  default:
    name: student-network
    driver: bridge