version: '3'

services:
  grafana:
    image: grafana/grafana:8.2.2
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin

  influxdb:
    image: influxdb:2.0-alpine
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - ./data/influxdb2/data:/var/lib/influxdb2
      - ./data/influxdb2/config:/etc/influxdb2
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: "false"
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: user
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: my-org
      DOCKER_INFLUXDB_INIT_BUCKET: my-bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: admin-token
      INFLUXD_REPORTING_DISABLED: "true"

networks:
  default:
    name: student-network
    driver: bridge