
DROP TABLE IF EXISTS student;

CREATE TABLE student (
  id INT AUTO_INCREMENT PRIMARY KEY,
  rut VARCHAR(10) NOT NULL,
  name VARCHAR(50) NOT NULL,
  birth DATE NOT NULL,
  gender VARCHAR(250) DEFAULT NULL
);

CREATE UNIQUE INDEX UNIQ_RUT ON student(rut);

CREATE TABLE user(
   id INT AUTO_INCREMENT PRIMARY KEY,
   username VARCHAR(50) NOT NULL,
   password VARCHAR(100) NOT NULL,
   salt VARCHAR(100) NOT NULL,
   token VARCHAR(500)
);

CREATE UNIQUE INDEX UNIQ_USERNAME ON user(username);